In [13]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT *
        FROM FACILITIES
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
(0, 'Tennis Court 1', 5, 25, 10000, 200)
(1, 'Tennis Court 2', 5, 25, 8000, 200)
(2, 'Badminton Court', 0, 15.5, 4000, 50)
(3, 'Table Tennis', 0, 5, 320, 10)
(4, 'Massage Room 1', 9.9, 80, 4000, 3000)
(5, 'Massage Room 2', 9.9, 80, 4000, 3000)
(6, 'Squash Court', 3.5, 17.5, 5000, 80)
(7, 'Snooker Table', 0, 5, 450, 15)
(8, 'Pool Table', 0, 5, 400, 15)

In [14]:
#Q10
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
SELECT * FROM
(SELECT Facilities.name as facility_name, SUM((( Bookings.memid !=0 ) * membercost + ( Bookings.memid !=0 ) * guestcost)*Bookings.slots) AS revenue
FROM Bookings
JOIN Facilities
  ON Bookings.facid = Facilities.facid
JOIN Members
  ON Bookings.memid = Members.memid
GROUP BY Facilities.name) AS temp
WHERE revenue < 1000
ORDER BY revenue
        """
    cur.execute(query1)
 
    rows = cur.fetchall()

    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks

In [21]:
#Q11
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
SELECT m1.surname, m1.firstname, m2.surname  || ' ' || m2.firstname as recommeded_by
FROM Members m1 JOIN Members m2
  ON m1.recommendedby = m2.memid
ORDER BY m1.surname, m1.firstname
        """
    cur.execute(query1)
 
    rows = cur.fetchall()

    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Bader', 'Florence', 'Stibbons Ponder')
('Baker', 'Anne', 'Stibbons Ponder')
('Baker', 'Timothy', 'Farrell Jemima')
('Boothe', 'Tim', 'Rownam Tim')
('Butters', 'Gerald', 'Smith Darren')
('Coplin', 'Joan', 'Baker Timothy')
('Crumpet', 'Erica', 'Smith Tracy')
('Dare', 'Nancy', 'Joplette Janice')
('Genting', 'Matthew', 'Butters Gerald')
('Hunt', 'John', 'Purview Millicent')
('Jones', 'David', 'Joplette Janice')
('Jones', 'Douglas', 'Jones David')
('Joplette', 'Janice', 'Smith Darren')
('Mackenzie', 'Anna', 'Smith Darren')
('Owen', 'Charles', 'Smith Darren')
('Pinker', 'David', 'Farrell Jemima')
('Purview', 'Millicent', 'Smith Tracy')
('Rumney', 'Henrietta', 'Genting Matthew')
('Sarwin', 'Ramnaresh', 'Bader Florence')
('Smith', 'Jack', 'Smith Darren')
('Stibbons', 'Ponder', 'Tracy Burton')
('Worthington-Smyth', 'Henry', 'Smith Tracy')

In [18]:
#Q12
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
SELECT Facilities.name, COUNT(bookid)*(memid != 0) as member_usage
FROM Bookings
  JOIN Facilities
  ON Bookings.facid = Facilities.facid
GROUP BY Bookings.facid
        """
    cur.execute(query1)
 
    rows = cur.fetchall()

    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Tennis Court 1', 408)
('Tennis Court 2', 0)
('Badminton Court', 383)
('Table Tennis', 403)
('Massage Room 1', 629)
('Massage Room 2', 0)
('Squash Court', 0)
('Snooker Table', 444)
('Pool Table', 836)

In [22]:
#13
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
SELECT name as facility_name, strftime('%m', starttime) as month, COUNT(bookid)*(memid !=0) AS member_usage
FROM Bookings
JOIN Facilities
ON Bookings.facid = Facilities.facid
GROUP BY strftime('%m', starttime), Facilities.facid
        """
    cur.execute(query1)
 
    rows = cur.fetchall()

    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Tennis Court 1', '07', 88)
('Tennis Court 2', '07', 0)
('Badminton Court', '07', 56)
('Table Tennis', '07', 51)
('Massage Room 1', '07', 123)
('Massage Room 2', '07', 0)
('Squash Court', '07', 0)
('Snooker Table', '07', 75)
('Pool Table', '07', 110)
('Tennis Court 1', '08', 146)
('Tennis Court 2', '08', 149)
('Badminton Court', '08', 146)
('Table Tennis', '08', 147)
('Massage Room 1', '08', 224)
('Massage Room 2', '08', 40)
('Squash Court', '08', 0)
('Snooker Table', '08', 159)
('Pool Table', '08', 291)
('Tennis Court 1', '09', 0)
('Tennis Court 2', '09', 0)
('Badminton Court', '09', 181)
('Table Tennis', '09', 205)
('Massage Room 1', '09', 282)
('Massage Room 2', '09', 0)
('Squash Court', '09', 0)
('Snooker Table', '09', 210)
('Pool Table', '09', 435)